plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'own.watchface'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "own.watchface"
        minSdk 36
        targetSdk 37
        versionCode 1
        versionName "1.1"

    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    enableKotlin false
}

dependencies {
}